# Generated by Django 2.0.8 on 2018-11-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='content_type',
            new_name='target',
        ),
    ]
