# Generated by Django 2.0.8 on 2018-12-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_auto_20181123_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes_count',
        ),
    ]
