# Generated by Django 2.0.8 on 2018-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
