# Generated by Django 2.0.8 on 2018-12-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20181129_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='images',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='review',
            name='video',
        ),
    ]
