# Generated by Django 2.0.8 on 2018-12-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20181123_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
