# Generated by Django 2.0.8 on 2018-12-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='video',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
